language: java

jdk:
  - openjdk17

cache:
  directories:
    - '$HOME/.m2/repository'

install:
  - mvn install -DskipTests -Dmaven.source.skip=true -Dmaven.javadoc.skip=true -Dgpg.skip

script:
  - mvn clean package -DskipTests -Dmaven.source.skip=true -Dmaven.javadoc.skip=true -Dgpg.skip
